### ISSUE TITLE
Simplify notification and subscription process (also for tags)

### ISSUE THREAD

**Issue by flosse** [kartevonmorgen/kvmflows#8]
Board for Subscriptions: https://github.com/orgs/kartevonmorgen/projects/4?fullscreen=true
### Prerequisites
- [x] Use an external mail service kartevonmorgen/openfairdb#259
- [x] https://github.com/kartevonmorgen/openfairdb/issues/202
- [x] https://github.com/kartevonmorgen/openfairdb/issues/194
- [x] https://github.com/kartevonmorgen/openfairdb/issues/166 and 

### Target Group
Only a few power users will use the subscriptions, but those are the users, that improve the quality. So If we empower them, we improve the map qualitiy to all users, thats why it is a feature für all users.

### Problem
- Notifications are difficult to activate and if they come, there are too many with little intrest. To get more people beeing involved in mapping and ensuring content quality
- Its much too complicated to delete or to modify a subscription.

## Solution
- [x] Add Subscribe-Button [#443](https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/151)

### Just allow to subscribe to any search and map view

- [ ] Rather usefull i think would be the option to **subscribe to hashtags**. So on the page where you choose the area, you also have the searchline to put in some keywords and tags. Especially if there are coming the events. But also like this it would help the theme-pilots to subscribe to alle csa-projects in the world. but only csa. https://github.com/kartevonmorgen/kvmflows/issues/5

- [ ] Subscribe to single entries, also **while editing**. https://github.com/kartevonmorgen/kartevonmorgen/issues/635 

- [ ] We should definitly include **Positive Impact Ratings** in the notification-System.  https://github.com/kartevonmorgen/kvmflows/issues/7 (More imprtant than the question, if an entry is on the map, is the question, how good it is rated. )

- [ ] Notify users at maximum once a day: **Only send notification Mail after there was no editing for at least 30 min.** Otherwise we spam users too much with notifications if we send it evrey minute and someone is just trying how the map works...  Maybe even just once a day https://github.com/kartevonmorgen/kvmflows/issues/9

- [ ] **Unsybscribe link in every notification-mail** https://github.com/kartevonmorgen/kvmflows/issues/4 . Each subscription is saved so you can delete every single subscription with an link in the mail. 

### Fazit 
- from David:
However I find one menu better: simpler, I don't need to search where I can find something but everything is in one place, the `Kartenausschnitt abonnieren`-thing doesn't really fit under `share`, I'm rather "sharing" it with myself, and we might have more features in the future that don't really fit in these two categories and if we put them there anyway it gets confusing for users.
- Helmut:
I think the Hamburger Menu contains everything, that leaves the map. The sharing menu has everything, that works on the map with popups. 
As subscription is much simpler in the future and works as a popup, it should be in the sharing button.
